---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json

controllers:
  main:
    # -- Set the controller upgrade strategy
    strategy: Recreate

    containers:
      # Configure the main application container
      main:
        image: &image
          # -- image repository
          repository: freshrss/freshrss
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 1.27.1

        env:
          CRON_MIN: '*/20'
        
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi

        probes:
          # -- Configures liveness probe
          liveness:
            type: HTTP
            path: /i/
          # -- Configures readiness probe
          readiness:
            type: HTTP
            path: /i/

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  data:
    retain: true
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /var/www/FreshRSS/data
    # storageClass: ""
  extensions:
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /var/www/FreshRSS/extensions
