---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/values.schema.json

controllers:
  rsshub:
    # -- Set the controller upgrade strategy
    strategy: RollingUpdate

    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/diygod/rsshub
          # -- image pull policy
          pullPolicy: Always
          # -- image tag
          tag: latest

        # -- environment variables.
        # @default -- See [values.yaml](./values.yaml)
        env:
          NODE_ENV: production
          CACHE_TYPE: redis
          REDIS_URL: "redis://rsshub-redis:6379/"
          PUPPETEER_WS_ENDPOINT: ws://rsshub-browserless:3000

        probes:
          # -- Configures liveness probe
          liveness:
            type: HTTP
            path: /healthz
          # -- Configures readiness probe
          readiness:
            type: HTTP
            path: /healthz

  redis:
    containers:
      main:
        image:
          repository: ghcr.io/valkey-io/valkey
          tag: 9.0.0

        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            memory: 256Mi

  browserless:
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: ghcr.io/browserless/chrome
          tag: v2.37.1

        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 2Gi

        probes:
          liveness:
            type: HTTP
            path: /pressure
          readiness:
            type: HTTP
            path: /pressure

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  rsshub:
    controller: rsshub
    ports:
      http:
        port: 1200
  redis:
    controller: redis
    ports:
      redis:
        port: 6379
  browserless:
    controller: browserless
    ports:
      ws:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         service:
    #           identifier: rsshub
    #           port: http
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local
