---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json

controllers:
  main:
    # -- Set the controller upgrade strategy
    strategy: RollingUpdate

    containers:
      rsshub:
        image:
          # -- image repository
          repository: ghcr.io/diygod/rsshub
          # -- image pull policy
          pullPolicy: Always
          # -- image tag
          tag: latest

        # -- environment variables.
        # @default -- See [values.yaml](./values.yaml)
        env:
          NODE_ENV: production
          CACHE_TYPE: redis
          REDIS_URL: "redis://localhost:6379/"
          PUPPETEER_WS_ENDPOINT: ws://localhost:3000

        probes:
          # -- Configures liveness probe
          liveness:
            type: HTTP
            path: /healthz
          # -- Configures readiness probe
          readiness:
            type: HTTP
            path: /healthz

      redis:
        image:
          repository: ghcr.io/valkey-io/valkey
          tag: 8.1.3

        ports:
          - containerPort: 6379

        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            memory: 256Mi

      browserless:
        image:
          repository: ghcr.io/browserless/chrome
          tag: v2.37.0

        ports:
          - containerPort: 3000

        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 2Gi

        probes:
          liveness:
            type: HTTP
            path: /pressure
          readiness:
            type: HTTP
            path: /pressure

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    controller: main
    ports:
      http:
        port: 1200

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local
