# Default values for navidrome.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
nameOverride: ""
fullnameOverride: ""

# Image pull secrets
imagePullSecrets: []

# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod-level security context
podSecurityContext: {}
  # fsGroup: 2000

# Container-level security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Additional volumes
volumes: []

# Deployments configuration
deployments:
  main:
    replicaCount: 1
    image:
      repository: diygod/rsshub
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

    # Container ports
    ports:
      - name: http
        containerPort: 1200
        protocol: TCP
    
    # Environment variables
    env:
      NODE_ENV: production

    # Health checks
    livenessProbe:
      httpGet:
        path: /healthz
        port: http

    readinessProbe:
      httpGet:
        path: /healthz
        port: http

    # Resource limits and requests
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    # Autoscaling configuration
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

# Services configuration
services:
  main:
    type: ClusterIP
    ports:
      - name: http
        port: 1200
        targetPort: http
        protocol: TCP

# Ingress configuration
ingress:
  main:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

redis:
  enabled: true
  replica:
    replicaCount: 0
