{{/*
Common HPA template
Usage:
{{- include "common.hpa" (dict "deploymentName" "main" "context" .) }}
*/}}
{{- define "common.hpa" -}}
{{- $deploymentName := .deploymentName -}}
{{- $context := .context -}}
{{- $deployment := index $context.Values.deployments $deploymentName -}}
{{- if and $deployment $deployment.autoscaling $deployment.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.deploymentName" . }}
  labels:
    {{- include "common.deploymentLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.deploymentName" . }}
  minReplicas: {{ $deployment.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $deployment.autoscaling.maxReplicas | default 100 }}
  metrics:
    {{- if $deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with $deployment.autoscaling.customMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if $deployment.autoscaling.behavior }}
  behavior:
    {{- toYaml $deployment.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
