{{/*
Common loader template - renders all Kubernetes resources based on values
Usage:
{{- include "common.loader" . }}
*/}}
{{- define "common.loader" -}}
{{- $context := . -}}

{{/* Service Account */}}
{{- include "common.serviceAccount" $context }}
---

{{/* Persistent Volume Claims */}}
{{- range $pvcName, $pvc := $context.Values.persistence }}
{{- include "common.pvc" (dict "pvcName" $pvcName "context" $context) }}
---
{{- end }}

{{/* Deployments */}}
{{- range $deploymentName, $deployment := $context.Values.deployments }}
{{- include "common.deployment" (dict "deploymentName" $deploymentName "context" $context) }}
---
{{- end }}

{{/* Services */}}
{{- range $serviceName, $service := $context.Values.services }}
{{- include "common.service" (dict "serviceName" $serviceName "context" $context) }}
---
{{- end }}

{{/* Ingress */}}
{{- range $ingressName, $ingress := $context.Values.ingress }}
{{- include "common.ingress" (dict "ingressName" $ingressName "context" $context) }}
---
{{- end }}

{{/* Horizontal Pod Autoscalers */}}
{{- range $deploymentName, $deployment := $context.Values.deployments }}
{{- include "common.hpa" (dict "deploymentName" $deploymentName "context" $context) }}
---
{{- end }}

{{- end -}}
