{{/*
Common service template
Usage:
{{- include "common.service" (dict "serviceName" "main" "context" .) }}
*/}}
{{- define "common.service" -}}
{{- $serviceName := .serviceName -}}
{{- $context := .context -}}
{{- $service := index $context.Values.services $serviceName -}}
{{- if $service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.serviceName" . }}
  labels:
    {{- include "common.labels" $context | nindent 4 }}
    {{- with $service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  {{- if and (eq $service.type "LoadBalancer") $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq $service.type "LoadBalancer") $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq $service.type "ClusterIP") $service.clusterIP }}
  clusterIP: {{ $service.clusterIP }}
  {{- end }}
  {{- if $service.externalIPs }}
  externalIPs:
    {{- range $service.externalIPs }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $service.externalTrafficPolicy }}
  {{- end }}
  {{- if $service.sessionAffinity }}
  sessionAffinity: {{ $service.sessionAffinity }}
  {{- end }}
  {{- if $service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml $service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  ports:
    {{- range $service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
      {{- if and (or (eq ($service.type | default "ClusterIP") "NodePort") (eq ($service.type | default "ClusterIP") "LoadBalancer")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- if $service.selector }}
    {{- toYaml $service.selector | nindent 4 }}
    {{- else }}
    {{- include "common.selectorLabels" $context | nindent 4 }}
    {{- if $service.component }}
    app.kubernetes.io/component: {{ $service.component }}
    {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
