{{/* Append the hardcoded settings */}}
{{- define "rsshub.hardcodedValues" -}}
deployments:
  main:
    env:
      {{- if .Values.redis.enabled }}
      CACHE_TYPE: redis
      REDIS_PASSWORD:
        secretKeyRef:
        name: {{ .Release.Name }}-redis
        key: redis-password
      REDIS_URL: "redis://:$(REDIS_PASSWORD)@{{ .Release.Name }}-redis-master:6379/"
      {{- end }}
{{- end -}}

{{/* Merge hardcoded values with user values */}}
{{- $_ := mergeOverwrite .Values (include "rsshub.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "common.loader" . }}
