image:
  # -- image repository
  repository: ghcr.io/autobrr/autobrr
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 7474

probes:
  # -- Configures liveness probe
  liveness:
    type: HTTP
    path: /api/healthz/liveness
  # -- Configures readiness probe
  readiness:
    type: HTTP
    path: /api/healthz/readiness

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

# -- Enable and configure redis subchart under this key.
#    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/main/bitnami/redis)
# @default -- See [values.yaml](./values.yaml)
redis:
  enabled: true
  replica:
    replicaCount: 0

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 500Mi
