---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json

controllers:
  main:
    # -- Set the controller upgrade strategy
    strategy: Recreate

    containers:
      autobrr:
        image:
          # -- image repository
          repository: ghcr.io/autobrr/autobrr
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: v1.66.1

        # -- environment variables.
        # @default -- See [values.yaml](./values.yaml)
        env: {}

        probes:
          # -- Configures liveness probe
          liveness:
            type: HTTP
            path: /api/healthz/liveness
          # -- Configures readiness probe
          readiness:
            type: HTTP
            path: /api/healthz/readiness

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    controller: main
    ports:
      http:
        port: 7474

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  config:
    retain: true
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /config
    # storageClass: ""
