{{/* Append the hardcoded settings */}}
{{- define "rsshub.harcodedValues" -}}
controllers:
  main:
    containers:
      rsshub:
        env:
          {{- if .Values.redis.enabled }}
          CACHE_TYPE: redis
          REDIS_PASSWORD:
            secretKeyRef:
              name: {{ .Release.Name }}-redis
              key: redis-password
          REDIS_URL: "redis://:$(REDIS_PASSWORD)@{{ .Release.Name }}-redis-master:6379/"
          {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "rsshub.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}