---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json

controllers:
  main:
    # -- Set the controller upgrade strategy
    strategy: RollingUpdate

    containers:
      navidrome:
        image:
          # -- image repository
          repository: deluan/navidrome
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 0.58.0
        
        # -- environment variables. [[ref]](https://www.navidrome.org/docs/usage/configuration-options/#environment-variables)
        # @default -- See [values.yaml](./values.yaml)
        env:
          ND_ENABLEINSIGHTSCOLLECTOR: false

        probes:
          # -- Configures liveness probe
          liveness:
            type: HTTP
            path: /ping
          # -- Configures readiness probe
          readiness:
            type: HTTP
            path: /ping

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    controller: main
    ports:
      http:
        port: 4533

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  config:
    retain: true
    accessMode: ReadWriteOnce
    size: 800Mi
    globalMounts:
      - path: /config
    # storageClass: ""
